# Generated by Django 6.1 on 2026-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_event_galleryimage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='person_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
