# Generated by Django 6.1 on 2026-08-10 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(default='Share Link', help_text='Organizer-visible label', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Hashed password (blank = no protection)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Leave blank for no expiry.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='gallery.event')),
            ],
        ),
    ]
