# Generated by Django 6.1 on 2026-08-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_event_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsharelink',
            name='person_label',
            field=models.CharField(blank=True, help_text='If set, limits access to this face group label only', max_length=100, null=True),
        ),
    ]
