# Generated by Django 6.1 on 2026-09-13 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Set to True if the user has paid, bypassing trial limits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_duration_days',
            field=models.IntegerField(default=7, help_text='Number of days the trial is valid'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
