# Generated by Django 6.1 on 2026-09-17 04:08

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_userprofile_is_paid_userprofile_trial_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='file',
            field=models.ImageField(upload_to=gallery.models.event_image_upload_path),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.event_thumbnail_upload_path),
        ),
    ]
