# Generated by Django 6.1 on 2026-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_galleryimage_file_alter_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsharelink',
            name='search_only',
            field=models.BooleanField(default=False, help_text='If true, guests can only upload a selfie to find their photos, and cannot browse the full gallery.'),
        ),
    ]
