# Generated by Django 6.1 on 2026-09-18 06:08

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_guestlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.event_cover_upload_path),
        ),
    ]
