# Generated by Django 6.1 on 2026-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_storage_limit_mb',
            field=models.IntegerField(blank=True, help_text='Override plan storage limit (in MB)', null=True),
        ),
    ]
