# Generated by Django 6.1 on 2026-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_userprofile_custom_storage_limit_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Store plain text password for admin reference', max_length=255, null=True),
        ),
    ]
