# Generated by Django 6.1 on 2026-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_userprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='compression_percentage',
            field=models.IntegerField(default=100, help_text='Image compression percentage (1-100). 100 means no extra compression.'),
        ),
    ]
